version: '2'
services:
  vm:
    image: centos:vm-golang-sv
    hostname: centos-ssh.demo
    container_name: vm_golang_demo
    restart: always
    ports:
      - "10022:22"
    networks:
      - common_network

networks:
  common_network:
    external: true  # 引用外部网络    