version: '2'
services:
  mysql:
    image: mysql:5.6
    container_name: db-mysql
    restart: always
    privileged: true
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "blogger"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "123456"
    volumes:
      - ./conf/my.cnf:/etc/mysql/my.cnf
      - ./data:/var/lib/mysql
    networks:
      - common_network
networks:
  common_network:
    external: true