version: '2'
services:
  redis:
    image: redis:latest
    container_name: golang-redis
    restart: always
    ports:
      - 0.0.0.0:6379:6379
    volumes:
      - ./data:/data
      - ./conf/redis.conf:/data/redis.conf
    entrypoint:
      - redis-server
      - /data/redis.conf
    networks:
      - common_network
networks:
  common_network:
    external: true

